### ISSUE TITLE
add2 + standoff creates undesired holes on top and bottom

### ISSUE THREAD

**Issue by tomek-szczesny** [hominoids/SBC_Case_Builder#24]
I guess the idea behind standoffs was to put them either on top or bottom of a case, as the code suggests it automatically makes holes for add2 class:

https://github.com/hominoids/SBC_Case_Builder/blob/33e9c04da10243e7fb8f548405a73253eb2e5be7/sbc_case_builder.scad#L1202-L1206

Took me a while to figure out what is going on. :) Picture below. Holes are created regardless how standoff is oriented or how high it is above the case bottom.

Code:
```
"sub","round",111,16.57,9,"bottom",[0,90,0],["case",true,false,false],9,0,4,0,0,"",0,                                    // vent cover screw hole
"add2","standoff",140,16.57,9 ,"bottom",[0,90,0],["case",false,false,false],0,0,0,0,0,0,[10,4,3.2,10,2.5,3,1,0,0,0,0], // standoff
```
In another words, a horizontal 10mm standoff stuffed into a 9mm hole. 

Any way to work around this issue? I could use add1 instead but I do need to make a hole first to obtain recessed nut holder.

![2023-01-15-202301_1427x501_scrot](https://user-images.githubusercontent.com/44300715/212562602-abdca6ce-92fc-40e8-a87e-bab40f5ecf1a.png)

**Comment by hominoids** [comment]
Thanks for the issue report.  It has been addressed in the latest commit as well as the unreported issue you identified with the standoff sidewall support for the top of cases.
