### ISSUE TITLE
rock5b v1.3 case verified

### ISSUE THREAD

**Issue by amazingfate** [hominoids/SBC_Case_Builder#28]
Hello , finally I got my printed case for my rock5b v1.3 developer edition.
It works but still has some minor issues.
At first I cant't install the case because of the audio jack opening:
![image](https://user-images.githubusercontent.com/5022901/218931711-53c65245-4422-4d1c-92bb-3a31e4e4a6a0.png)
Then I cut one part of the audio jack opening, then here comes the typec opening:
![image](https://user-images.githubusercontent.com/5022901/218931856-ecd65d24-52a6-433f-bd51-e5ce0cb2428d.png)
Then I cut one part of the typec opening, here is the final state:
![image](https://user-images.githubusercontent.com/5022901/218931994-6b7237c3-4967-4c06-8dd2-57090af1d969.png)

There is another issue that the power button position is not right:
![image](https://user-images.githubusercontent.com/5022901/218932134-5748450a-8bd5-4789-9bf9-c167a1487c5d.png)

I use the position of audio jack, typec and power button same as rock5b v1.42 in your repo. This is just a feedback from rock5b v1.3. We need users who can verify this on rock5b v1.42.

**Comment by hominoids** [comment]
After waiting more then 2 months my ROCK5B arrived a couple of days ago.  I did one test prints and made a few adjustments for the 1.42v yesterday.  I have another adjustment to do and test print and it should be complete.  I'll post the corrections I made soon.  Has the status of the 1.3v changed?

**Comment by amazingfate** [comment]
There are some differences between v1.3 and v1.42. I may create pull request to add adjustments on v1.3 in the future. There are only 50 V1.3 boards in the world, so not many people need this.
