### ISSUE TITLE
Rock 5B case issues

### ISSUE THREAD

**Issue by Chippit** [hominoids/SBC_Case_Builder#31]
The Rock5B case templates have some minor issues.

- All top pieces have two unneeded cylinders on them
- The snap case top part only has snaps on one side

The image below illustrates both problems

![image](https://github.com/hominoids/SBC_Case_Builder/assets/870779/7443074e-a386-4144-84c5-e5895375c68b)

**Comment by hominoids** [comment]
Thanks for reporting the problems, they are fixed in the recent commit.  Let me know if you have anymore issues.
