### ISSUE TITLE
Adding support for Open Pi board

### ISSUE THREAD

**Issue by samuk** [hominoids/SBC_Case_Builder#32]
Would you be interested in adding a case for: https://pipci.jeffgeerling.com/boards_cm/johanns_carrier_board.html I hope to make them available for sale soon. The boards will be CERN-OHL-P open hardware

The step is https://github.com/samuk/Open-Pi/tree/main/v1/3d

**Comment by hominoids** [comment]
Hi Samuk,
The cases are autonomously generated from the SBC that are part of SBC 
Model Framework.  To have SBC Case Builder generate cases for your 
carrier board it needs to be added to SBC Model Framework.  After it is 
added any of the cases in SBCCB can be generated with or without further 
case customization.

After an extended development cycle, I'm on the cusp of releasing 
version 2.0 of SBC Model Framework.  It's schema is significantly 
different then version 1 and has features that will make adding boards 
much easier, so I would recommend using version 2. It is usable in it's 
current beta state and can be viewed at this branch:
https://github.com/hominoids/SBC_Model_Framework/tree/v2update

I'm currently adding more SBC, MCU and updating documentation.  I 
estimate that it will take between 1-2 weeks to finalize, release 
version 2.0 and integrate it into SBC Case Builder. As chance would have 
it, the RPi CM4 and IO board were recently added to v2 so it can be used 
as a reference.

Are you the original designer of this board or just marketing it?
What is the release timeline?
What is the scope and magnitude of your planned 1st production?
Does this carrier board/project have a name?

hominoid

**Comment by samuk** [comment]
Hi thanks, I might just check in in two weeks. I have time.

I'm not the designer of the board, I'm just marketing & hopefully certifying it. I was given the design files on condition that it was professionally reviewed which I intend to do.

Timeline, a month or so until I have some [uncertified engineering samples](https://github.com/samuk/Open-Pi/blob/main/compliance/EvaluationBoards.md) 

I may do a 20pc run of engineering samples after an initial 5pc batch.

Not sure on actual CE marked boards, never done it before. Several months at least. 

I'm calling it 'Open Pi' for now but need to check how sensible that is https://github.com/samuk/Open-Pi/tree/main

**Comment by hominoids** [comment]
SBC Model Framework v2 and SBC Case Builder are ready.  I have attached a sample sbc_models.cfg entry for SBC Model Framework that includes the PCB, 4 holes and the GPIO already placed.  It will get you a solid start and you will just need to place the remaining components.

![test_jocabo](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/3837ca09-2a20-4587-a919-e88ae1ed1294)

To that end here is a simple OpenSCAD program that overlays a STL file that was converted from your STEP model.  This way components can be visually placed.  Make sure to have SBC_Model_Framework in the current directory or update the <use> statement.  When it's complete issue a PR to include it in the distribution.
```
use <./sbc_models.scad>
model = "jocabo";

rotate([0,0,90]) import("jocabo.stl");

sbc(model, "default", 0, "default", "default", false);
// uncomment to display the mask
//#sbc(model, "default", 0, "default", "default", true);

```
[test_jocabo_sbc_models.txt](https://github.com/hominoids/SBC_Case_Builder/files/14223270/test_jocabo_sbc_models.txt)
[jocabo.stl.zip](https://github.com/hominoids/SBC_Case_Builder/files/14223280/jocabo.stl.zip)

[How to add a New SBC or MCU](https://github.com/hominoids/SBC_Model_Framework#adding-devices)

[SBC Model Framework Reference Manual](https://github.com/hominoids/SBC_Model_Framework#class-and-type-reference-manual)

Good luck with your project!
