### ISSUE TITLE
Thank you and questions for a 20cm tall case...

### ISSUE THREAD

**Issue by vijaygill** [hominoids/SBC_Case_Builder#40]
Hi,

First of all, thanks for such a great piece of software. I tried I could really play with various designs.

Now, I am trying to create a case for Rock 5A based nas (the SBC has same layour as Raspberry Pi 4C) using Radxa Penta SATA HAT. When I set tz value to say 200 to get a really tall case, I find two limitations

1. I foresee problem in installing the board. Is there a way I can have that lid at the top taller so that lower part can be made shorter?
2. I cannot seem to add a fan on the side wall. Is this to be done as post-design step in another editor or can the framework achieve it too? I deally I would like to add fan at the top, I was just trying to add it on the side in the design.

Thank you once again and apoligies in advance if my requirements are too stupid.

![image](https://github.com/user-attachments/assets/95f0f9e6-9ffb-4b84-a55b-e4b7c2e32432)

**Comment by hominoids** [comment]
The Fitted case top is a fixed height and cannot be changed but that won't solve the problem your likely to have during installation anyway.  Setting the gap value correctly should solve the SBC installation issue and allow it to be installed regardless of the case bottom height. In the *3D Case Adjustments* Tab, increase the gap so there is very little to no protrusion of any component overhang thru the sidewall. The README.md briefly talks about [component overhang and case gap](https://github.com/hominoids/SBC_Case_Builder?tab=readme-ov-file#component-overhang-and-case-gap ).

As far as the second issue goes, fan mask patterns cannot be 3D printed on a vertical sidewall AFAIK, but a round opening can be created for use with a fan cover as an accessory.  There are saved examples such as hc4_shell_drivebox2.5 that use this technique.  
![sidewall_fan_opening](https://github.com/user-attachments/assets/d4bdc2e2-611e-4e63-8369-fbd6db29f2d8)
It uses the following accessory entries to create a sidewall fan opening and fan cover.  Something similar should work for your case.
```
"model","fan",39,10,7.5,"bottom",[90,0,0],["case",true,false,false],[40,0,3],["box40x10"],[true,10,2,"fan_open"],
"model","fan_cover",39,-4,7.5,"bottom",[90,0,0],["case",true,false,false],[40,0,3],["fan_1"],[false,10,2,"default"],
"platter","fan_cover",-50,50,0,"bottom",[0,0,0],["case",false,false,false],[40,0,3],["fan_1"],[false,10,2,"default"],

```
You'll need to create and assign an accessory group to your case, look at the examples and read the [Accessory subsystem and use](https://github.com/hominoids/SBC_Case_Builder?tab=readme-ov-file#accessory-subsystem) section in the README.md file.

Accessory Reference Entries
https://github.com/hominoids/SBC_Case_Builder#fan
https://github.com/hominoids/SBC_Case_Builder#fan_cover

**Comment by vijaygill** [comment]
@hominoids Thanks once again for a detailed reply. I wil try as per your suggestion.
