### ISSUE TITLE
Alternative to setting standoff hole parameters

### ISSUE THREAD

**Issue by davejlong** [hominoids/SBC_Case_Builder#6]
Instead of having to specific numeric values for standoff holes, would it make more sense to instead just enter the type of screw used and build the holes off of that? For example, the standard screw for PCB holes is M2.5, so the bottom standoff hole should be 2.5mm. If setting a nut holder type hole, the nut for an M2.5 screw is 4.9mm, so the hole should be ~5mm. 

![Nut Size Reference](https://user-images.githubusercontent.com/175317/181356847-f2a07d25-e7c0-4877-8fa5-4d4b304bcafa.jpg)

**Comment by hominoids** [comment]
That sounds good on the surface but I'm concerned that it might create limitations with so many diverse users.  For instance, tapping holes as one example.  The size of the hole does vary based on the strength and shrinkage of the material one might use.  Same thing with nuts to be inserted.  I sometimes reduce the opening and hot insert them when they need to stay in place.  This change would make it easier for some but also less flexible for others.   I like the thought behind the suggestion but not sure of all the consequences.  I think we should hold off for now which would give more time to think about all the possible ramifications.

**Comment by hominoids** [comment]
Not implemented for now.
