### ISSUE TITLE
Feature Request: Support for different height standoffs

### ISSUE THREAD

**Issue by davejlong** [hominoids/SBC_Case_Builder#9]
I use the [GeeekPi PoE Hat](https://smile.amazon.com/dp/B08CVDQWXF) for my Raspberry Pis which attaches to the pi at 3 points using standoffs. This means that creating a case for it, I need 3 of the standoffs to be short to screw into the PoE Hat and 1 standoff to be longer to reach down to the Pi. Right now this isn't possible. I think it would be suitably easy to add an option to provide an offset for each standoff.

**Comment by hominoids** [comment]
I agree and this aligns with the broader issue of add on PCBs that I have been mulling over.

**Comment by hominoids** [comment]
This is now complete.
